# Generated by Django 5.1.1 on 2025-06-04 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('edms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='signaturelog',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signature_logs', to='edms.document'),
        ),
        migrations.AddField(
            model_name='signaturelog',
            name='signer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signature_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='signaturerequest',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signature_requests', to='edms.document'),
        ),
        migrations.AddField(
            model_name='signaturerequest',
            name='signer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signature_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='signaturelog',
            name='signature_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='edms.signaturerequest'),
        ),
        migrations.AlterUniqueTogether(
            name='document',
            unique_together={('category', 'version_number')},
        ),
        migrations.AlterUniqueTogether(
            name='signaturerequest',
            unique_together={('document', 'signer', 'page_number', 'x_position', 'y_position')},
        ),
    ]
