# Generated by Django 5.1.1 on 2025-06-04 07:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255, null=True)),
                ('name_vi', models.CharField(max_length=255, null=True)),
                ('name_zh_hant', models.CharField(max_length=255, null=True)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('select', 'Select'), ('file', 'File'), ('json', 'Table'), ('assignee', 'Assignee')], default='text', max_length=255)),
                ('order', models.PositiveSmallIntegerField()),
                ('required', models.BooleanField(default=False)),
                ('options', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProcessUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255, null=True)),
                ('name_vi', models.CharField(max_length=255, null=True)),
                ('name_zh_hant', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('description_vi', models.TextField(blank=True, null=True)),
                ('description_zh_hant', models.TextField(blank=True, null=True)),
                ('version', models.CharField(max_length=255)),
                ('prefix', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('name', 'version'), name='unique_process_version'), models.UniqueConstraint(fields=('name_en', 'version'), name='unique_process_version-name_en'), models.UniqueConstraint(fields=('name_vi', 'version'), name='unique_process_version-name_vi'), models.UniqueConstraint(fields=('name_zh_hant', 'version'), name='unique_process_version-name_zh_hant')],
            },
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255, null=True)),
                ('name_vi', models.CharField(max_length=255, null=True)),
                ('name_zh_hant', models.CharField(max_length=255, null=True)),
                ('description', models.TextField()),
                ('description_en', models.TextField(null=True)),
                ('description_vi', models.TextField(null=True)),
                ('description_zh_hant', models.TextField(null=True)),
                ('action_type', models.CharField(choices=[('approve', 'Approve'), ('adjust', 'Adjust'), ('confirm', 'Confirm'), ('complete', 'Complete'), ('close', 'Close'), ('reject', 'Reject'), ('cancel', 'Cancel')], max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.process')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessActionRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_type', models.CharField(choices=[('requestor', 'Task Requestor'), ('requestor_manager', 'Requestor Manager'), ('requestor_department_head', 'Requestor Department Head'), ('specific_department_head', 'Specific Department Head'), ('assignee', 'Task Assignee'), ('specific_user', 'Specific User'), ('specific_role', 'Specific Role'), ('specific_department', 'Specific Department'), ('specific_role_and_department', 'Specific Role and Department')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.action')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.process')),
            ],
        ),
    ]
