# Generated by Django 5.1.1 on 2025-05-02 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('process', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='processuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='processuseraction',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.action'),
        ),
        migrations.AddField(
            model_name='processuseraction',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.process'),
        ),
        migrations.AddField(
            model_name='processuseraction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='processfield',
            unique_together={('process', 'name')},
        ),
        migrations.AddConstraint(
            model_name='processuseraction',
            constraint=models.UniqueConstraint(fields=('process', 'user', 'action'), name='unique_process_user_action'),
        ),
    ]
