# Generated by Django 5.1.1 on 2025-06-04 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('process', '0001_initial'),
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='processactionrole',
            name='specific_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.department'),
        ),
        migrations.AddField(
            model_name='processactionrole',
            name='specific_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.role'),
        ),
        migrations.AddField(
            model_name='processactionrole',
            name='specific_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='processfield',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='process.process'),
        ),
        migrations.AddField(
            model_name='processuser',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_users', to='process.process'),
        ),
        migrations.AddField(
            model_name='processuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='processactionrole',
            constraint=models.UniqueConstraint(fields=('process', 'action', 'role_type', 'specific_user', 'specific_role', 'specific_department'), name='unique_process_action_role'),
        ),
        migrations.AddConstraint(
            model_name='processfield',
            constraint=models.UniqueConstraint(fields=('process', 'name'), name='unique_process_field'),
        ),
        migrations.AddConstraint(
            model_name='processfield',
            constraint=models.UniqueConstraint(fields=('process', 'name_en'), name='unique_process_field-name_en'),
        ),
        migrations.AddConstraint(
            model_name='processfield',
            constraint=models.UniqueConstraint(fields=('process', 'name_vi'), name='unique_process_field-name_vi'),
        ),
        migrations.AddConstraint(
            model_name='processfield',
            constraint=models.UniqueConstraint(fields=('process', 'name_zh_hant'), name='unique_process_field-name_zh_hant'),
        ),
        migrations.AddConstraint(
            model_name='processuser',
            constraint=models.UniqueConstraint(fields=('process', 'user'), name='unique_process_user'),
        ),
    ]
