# Generated by Django 5.1.1 on 2025-05-04 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('select', 'Select'), ('multiselect', 'Multi-Select'), ('checkbox', 'Checkbox'), ('file', 'File'), ('json', 'Table')], default='text', max_length=255),
        ),
    ]
