# Generated by Django 5.1.1 on 2025-05-10 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0003_alter_processfield_field_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processfield',
            name='options',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('select', 'Select'), ('checkbox', 'Checkbox'), ('file', 'File'), ('json', 'Table')], default='text', max_length=255),
        ),
    ]
