# Generated by Django 5.1.1 on 2025-08-07 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0003_alter_processfield_field_type'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='processfield',
            name='unique_process_field',
        ),
        migrations.RemoveConstraint(
            model_name='processfield',
            name='unique_process_field-name_en',
        ),
        migrations.RemoveConstraint(
            model_name='processfield',
            name='unique_process_field-name_vi',
        ),
        migrations.RemoveConstraint(
            model_name='processfield',
            name='unique_process_field-name_zh_hant',
        ),
        migrations.AlterUniqueTogether(
            name='processfield',
            unique_together={('process', 'name')},
        ),
    ]
