# Generated by Django 5.1.1 on 2025-08-11 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0004_remove_processfield_unique_process_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processfield',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='processfield',
            name='description_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='processfield',
            name='description_vi',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='processfield',
            name='description_zh_hant',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
