# Generated by Django 5.1.1 on 2025-05-14 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0004_process_description_processfield_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processfield',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='processfield',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='processfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('select', 'Select'), ('checkbox', 'Checkbox'), ('file', 'File'), ('json', 'Table'), ('assignee', 'Assignee')], default='text', max_length=255),
        ),
    ]
