# Generated by Django 5.1.1 on 2025-05-17 08:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0005_alter_processfield_options_processfield_order_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='action_type',
            field=models.CharField(choices=[('initial', 'Initial'), ('approve', 'Approve'), ('adjust', 'Adjust'), ('confirm', 'Confirm'), ('complete', 'Complete'), ('close', 'Close'), ('reject', 'Reject'), ('cancel', 'Cancel')], default='initial', max_length=255),
        ),
        migrations.AlterField(
            model_name='processfield',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='processuser',
            name='process',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allowed_users', to='process.process'),
        ),
        migrations.AlterField(
            model_name='processuser',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='processuseraction',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions', to='process.action'),
        ),
        migrations.DeleteModel(
            name='ActionType',
        ),
    ]
