# Generated by Django 5.1.1 on 2025-09-07 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0005_processfield_description_processfield_description_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='process',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterField(
            model_name='process',
            name='is_active',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='processfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('select', 'Select'), ('file', 'File'), ('json', 'Table'), ('assignee', 'Assignee'), ('factory', 'Factory'), ('retailer', 'Retailer')], max_length=255),
        ),
        migrations.AlterField(
            model_name='processfield',
            name='required',
            field=models.BooleanField(),
        ),
    ]
