# Generated by Django 5.1.1 on 2025-05-17 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0006_alter_action_action_type_alter_processfield_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='process',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
