# Generated by Django 5.1.1 on 2025-09-12 03:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0006_alter_process_options_alter_process_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('time', 'Time'), ('select', 'Select'), ('multiselect', 'Multi Select'), ('file', 'File'), ('json', 'Table'), ('assignee', 'Assignee'), ('factory', 'Factory'), ('retailer', 'Retailer')], max_length=255),
        ),
        migrations.CreateModel(
            name='FieldCondition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operator', models.CharField(choices=[('exact', 'Exact'), ('not_exact', 'Not Exact'), ('contains', 'Contains'), ('not_contains', 'Not Contains'), ('in', 'In'), ('not_in', 'Not In'), ('gt', 'Greater Than'), ('lt', 'Less Than'), ('gte', 'Greater Than or Equal'), ('lte', 'Less Than or Equal'), ('is_empty', 'Is Empty'), ('is_not_empty', 'Is Not Empty'), ('weekday', 'Week day')], max_length=50)),
                ('value', models.JSONField(help_text='Value(s) to compare against')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('condition_field', models.ForeignKey(blank=True, help_text='The field to check the value of', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dependent_conditions', to='process.processfield')),
                ('field', models.ForeignKey(help_text='The field whose visibility this condition controls', on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='process.processfield')),
            ],
            options={
                'indexes': [models.Index(fields=['field', 'condition_field'], name='process_fie_field_i_282df4_idx')],
                'unique_together': {('field', 'condition_field', 'operator')},
            },
        ),
    ]
