# Generated by Django 5.1.1 on 2025-05-20 02:56

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0007_process_is_deleted_alter_process_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='processfield',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='process',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='action',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='action',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='process',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='process',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='process',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='process',
            name='version',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='processfield',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='processfield',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='processuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='processuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='processuseraction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='processuseraction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='action_type',
            field=models.CharField(choices=[('initial', 'Initial'), ('approve', 'Approve'), ('adjust', 'Adjust'), ('confirm', 'Confirm'), ('complete', 'Complete'), ('close', 'Close'), ('reject', 'Reject'), ('cancel', 'Cancel')], max_length=255),
        ),
        migrations.AlterField(
            model_name='processfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('select', 'Select'), ('file', 'File'), ('json', 'Table'), ('assignee', 'Assignee')], default='text', max_length=255),
        ),
        migrations.AlterField(
            model_name='processfield',
            name='order',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AddConstraint(
            model_name='process',
            constraint=models.UniqueConstraint(fields=('name', 'version'), name='unique_process_version'),
        ),
        migrations.AddConstraint(
            model_name='processfield',
            constraint=models.UniqueConstraint(fields=('process', 'name'), name='unique_process_field'),
        ),
        migrations.AddConstraint(
            model_name='processuser',
            constraint=models.UniqueConstraint(fields=('process', 'user'), name='unique_process_user'),
        ),
    ]
