# Generated by Django 5.1.1 on 2025-10-03 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0007_alter_processfield_field_type_fieldcondition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('time', 'Time'), ('select', 'Select'), ('multiselect', 'Multi Select'), ('file', 'File'), ('multifile', 'Multi File'), ('json', 'Table'), ('assignee', 'Assignee'), ('factory', 'Factory'), ('retailer', 'Retailer')], max_length=255),
        ),
    ]
