# Generated by Django 5.1.1 on 2025-10-07 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0008_alter_processfield_field_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldcondition',
            name='operator',
            field=models.CharField(choices=[('exact', 'Exact'), ('not_exact', 'Not Exact'), ('contains', 'Contains'), ('not_contains', 'Not Contains'), ('in', 'In'), ('not_in', 'Not In'), ('gt', 'Greater Than'), ('lt', 'Less Than'), ('gte', 'Greater Than or Equal'), ('lte', 'Less Than or Equal'), ('is_empty', 'Is Empty'), ('is_not_empty', 'Is Not Empty'), ('weekday', 'Week day'), ('user_dept', 'User Department'), ('user_dept_in', 'User Department In'), ('user_dept_not_in', 'User Department Not In')], max_length=50),
        ),
    ]
