# Generated by Django 5.1.1 on 2025-05-20 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0008_alter_processfield_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='version',
            field=models.CharField(max_length=255),
        ),
    ]
