# Generated by Django 5.1.1 on 2025-05-24 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0010_alter_processuser_process_alter_processuser_user'),
        ('user', '0004_alter_user_department_alter_user_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='prefix',
            field=models.CharField(default='AA', max_length=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ProcessActionRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_type', models.CharField(choices=[('requestor', 'Task Requestor'), ('requestor_manager', 'Requestor Manager'), ('department_head', 'Department Head'), ('assignee', 'Task Assignee'), ('specific_user', 'Specific User'), ('specific_role', 'Specific Role'), ('specific_department', 'Specific Department')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions', to='process.action')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.process')),
                ('specific_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.department')),
                ('specific_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.role')),
                ('specific_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ProcessUserAction',
        ),
        migrations.AddConstraint(
            model_name='processactionrole',
            constraint=models.UniqueConstraint(fields=('process', 'action', 'role_type', 'specific_user', 'specific_role', 'specific_department'), name='unique_process_action_role'),
        ),
    ]
