# Generated by Django 5.1.1 on 2025-05-24 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0011_process_prefix_processactionrole_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processactionrole',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.action'),
        ),
        migrations.AlterField(
            model_name='processactionrole',
            name='role_type',
            field=models.CharField(choices=[('requestor', 'Task Requestor'), ('requestor_manager', 'Requestor Manager'), ('requestor_department_head', 'Requestor Department Head'), ('specific_department_head', 'Specific Department Head'), ('assignee', 'Task Assignee'), ('specific_user', 'Specific User'), ('specific_role', 'Specific Role'), ('specific_department', 'Specific Department')], max_length=50),
        ),
    ]
