# Generated by Django 5.1.1 on 2025-05-26 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0013_alter_processuser_process_alter_processuser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processactionrole',
            name='role_type',
            field=models.CharField(choices=[('requestor', 'Task Requestor'), ('requestor_manager', 'Requestor Manager'), ('requestor_department_head', 'Requestor Department Head'), ('specific_department_head', 'Specific Department Head'), ('assignee', 'Task Assignee'), ('specific_user', 'Specific User'), ('specific_role', 'Specific Role'), ('specific_department', 'Specific Department'), ('specific_role_and_department', 'Specific Role and Department')], max_length=50),
        ),
    ]
