# Generated by Django 5.1.1 on 2025-06-03 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0014_alter_processactionrole_role_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='action_type',
            field=models.CharField(choices=[('approve', 'Approve'), ('adjust', 'Adjust'), ('confirm', 'Confirm'), ('complete', 'Complete'), ('close', 'Close'), ('reject', 'Reject'), ('cancel', 'Cancel')], max_length=255),
        ),
    ]
