# Generated by Django 5.1.1 on 2025-11-08 01:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='stop',
            constraint=models.UniqueConstraint(fields=('trip', 'order'), name='unique_trip_order'),
        ),
        migrations.AddConstraint(
            model_name='trip',
            constraint=models.UniqueConstraint(fields=('license_plate', 'driver', 'date'), name='unique_driver_license_plate_date'),
        ),
    ]
