# Generated by Django 5.1.1 on 2025-06-04 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('process', '0002_initial'),
        ('task', '0001_initial'),
        ('workflow_engine', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.process'),
        ),
        migrations.AddField(
            model_name='task',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow_engine.state'),
        ),
        migrations.AddField(
            model_name='taskactionlog',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.action'),
        ),
        migrations.AddField(
            model_name='taskactionlog',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='task.task'),
        ),
        migrations.AddField(
            model_name='taskactionlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskdata',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.processfield'),
        ),
        migrations.AddField(
            model_name='taskdata',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='task.task'),
        ),
        migrations.AddConstraint(
            model_name='taskdata',
            constraint=models.UniqueConstraint(fields=('task', 'field'), name='unique_task_field'),
        ),
    ]
