# Generated by Django 5.1.1 on 2025-05-07 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskactionlog',
            name='transition',
        ),
    ]
