# Generated by Django 5.1.1 on 2025-05-14 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_remove_taskactionlog_transition'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskUser',
        ),
    ]
