# Generated by Django 5.1.1 on 2025-07-02 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_taskfiledata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskactionlog',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='task_logs/'),
        ),
        migrations.AlterField(
            model_name='taskfiledata',
            name='uploaded_file',
            field=models.FileField(upload_to='uploads/task_data_files/'),
        ),
    ]
