# Generated by Django 5.1.1 on 2025-05-17 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_taskactionlog_comment_taskdata_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskdata',
            name='json_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='taskdata',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='task_files/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='taskdata',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='task.task'),
        ),
        migrations.AlterField(
            model_name='taskdata',
            name='value',
            field=models.TextField(blank=True, null=True),
        ),
    ]
