# Generated by Django 5.1.1 on 2025-08-14 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_taskdatahistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskfiledata',
            options={'ordering': ['-uploaded_at']},
        ),
    ]
