# Generated by Django 5.1.1 on 2025-05-20 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_alter_task_options_alter_taskactionlog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(default='BT123', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
