# Generated by Django 5.1.1 on 2025-05-20 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_alter_task_title_alter_taskactionlog_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskdata',
            name='file',
        ),
        migrations.RemoveField(
            model_name='taskdata',
            name='json_data',
        ),
    ]
