# Generated by Django 5.1.1 on 2025-05-26 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0013_alter_processuser_process_alter_processuser_user'),
        ('task', '0010_remove_taskdata_file_remove_taskdata_json_data'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='taskdata',
            constraint=models.UniqueConstraint(fields=('task', 'field'), name='unique_task_field'),
        ),
    ]
