# Generated by Django 5.1.1 on 2025-05-27 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0011_taskdata_unique_task_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskactionlog',
            options={'ordering': ['-created_at']},
        ),
    ]
