# Generated by Django 5.1.1 on 2025-06-03 09:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0012_alter_taskactionlog_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskactionlog',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='task_logs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf', 'doc', 'docx', 'xls', 'xlsx'])]),
        ),
    ]
