# Generated by Django 5.1.1 on 2025-08-20 09:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StepTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('name_en', models.CharField(max_length=128, null=True, unique=True)),
                ('name_vi', models.CharField(max_length=128, null=True, unique=True)),
                ('name_zh_hant', models.CharField(max_length=128, null=True, unique=True)),
                ('short_name', models.CharField(max_length=128, unique=True)),
                ('short_name_en', models.CharField(max_length=128, null=True, unique=True)),
                ('short_name_vi', models.CharField(max_length=128, null=True, unique=True)),
                ('short_name_zh_hant', models.CharField(max_length=128, null=True, unique=True)),
                ('spec', models.TextField(blank=True)),
                ('spec_en', models.TextField(blank=True, null=True)),
                ('spec_vi', models.TextField(blank=True, null=True)),
                ('spec_zh_hant', models.TextField(blank=True, null=True)),
                ('hold_time', models.PositiveIntegerField()),
                ('consumption', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, help_text='Reason to create this step')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
