# Generated by Django 5.1.1 on 2025-08-23 14:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0001_initial'),
        ('task', '0007_alter_taskfiledata_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormularTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('viscosity', models.PositiveSmallIntegerField()),
                ('wft', models.PositiveIntegerField()),
                ('description', models.TextField(help_text='Reason to create this formular')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FinishingSheet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finishing_code', models.CharField(max_length=255)),
                ('name', models.CharField(blank=True)),
                ('sheen', models.CharField(blank=True, max_length=50)),
                ('dft', models.CharField(blank=True, max_length=50)),
                ('type_of_paint', models.CharField(blank=True, max_length=50)),
                ('type_of_substrate', models.CharField(blank=True, max_length=200)),
                ('finishing_surface_grain', models.CharField(blank=True, max_length=100)),
                ('sampler', models.CharField(blank=True, max_length=100)),
                ('chemical_waste', models.CharField(max_length=20)),
                ('conveyor_speed', models.CharField(max_length=100)),
                ('with_panel_test', models.BooleanField(default=False)),
                ('testing', models.BooleanField(default=False)),
                ('chemical_yellowing', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finishing_sheets', to='task.task')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updater', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=128)),
                ('ratio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qty', models.CharField(blank=True, max_length=50)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('formular_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='sheet.formulartemplate')),
            ],
        ),
    ]
