# Generated by Django 5.1.1 on 2025-08-24 13:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0002_formulartemplate_finishingsheet_producttemplate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttemplate',
            name='qty',
        ),
        migrations.AlterField(
            model_name='finishingsheet',
            name='chemical_waste',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='finishingsheet',
            name='conveyor_speed',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='finishingsheet',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_sheets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='finishingsheet',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_sheets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='formulartemplate',
            name='description',
            field=models.TextField(blank=True, help_text='Reason to create this formular'),
        ),
        migrations.AlterField(
            model_name='formulartemplate',
            name='wft',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producttemplate',
            name='unit',
            field=models.CharField(default='g', max_length=20),
        ),
        migrations.CreateModel(
            name='SheetRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_num', models.IntegerField()),
                ('spot', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('stepname_en', models.CharField(max_length=255)),
                ('stepname_vi', models.CharField(max_length=255)),
                ('stepname_zh_hant', models.CharField(max_length=255)),
                ('viscosity_en', models.TextField()),
                ('viscosity_vi', models.TextField()),
                ('viscosity_zh_hant', models.TextField()),
                ('spec_en', models.TextField()),
                ('spec_vi', models.TextField()),
                ('spec_zh_hant', models.TextField()),
                ('hold_time', models.CharField(max_length=50)),
                ('chemical_code', models.CharField(max_length=100)),
                ('consumption', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_sheet_rows', to=settings.AUTH_USER_MODEL)),
                ('formular_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sheet.formulartemplate')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='sheet.finishingsheet')),
                ('step_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sheet.steptemplate')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_sheet_rows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sheet', 'step_num'],
                'unique_together': {('sheet', 'step_num')},
            },
        ),
        migrations.CreateModel(
            name='RowProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_code', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=200)),
                ('ratio', models.CharField(max_length=50)),
                ('qty', models.CharField(max_length=50)),
                ('unit', models.CharField(max_length=20)),
                ('check_result', models.CharField(max_length=255)),
                ('correct_action', models.CharField(max_length=255)),
                ('te1_signature', models.CharField(max_length=100)),
                ('customer_signature', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_row_products', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_row_products', to=settings.AUTH_USER_MODEL)),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='sheet.sheetrow')),
            ],
            options={
                'ordering': ['row', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ProductionAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=50)),
                ('changes', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheet.sheetrow')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
