# Generated by Django 5.1.1 on 2025-08-24 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0003_remove_producttemplate_qty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finishingsheet',
            name='chemical_waste',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='finishingsheet',
            name='conveyor_speed',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='finishingsheet',
            name='dft',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='finishingsheet',
            name='finishing_code',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='finishingsheet',
            name='finishing_surface_grain',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='finishingsheet',
            name='name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='finishingsheet',
            name='sampler',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='finishingsheet',
            name='sheen',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='finishingsheet',
            name='type_of_paint',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='finishingsheet',
            name='type_of_substrate',
            field=models.CharField(max_length=200),
        ),
    ]
