# Generated by Django 5.1.1 on 2025-09-07 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0005_alter_rowproduct_check_result_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finishingsheet',
            name='chemical_yellowing',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='finishingsheet',
            name='testing',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='finishingsheet',
            name='with_panel_test',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='rowproduct',
            name='order',
            field=models.PositiveIntegerField(),
        ),
    ]
