# Generated by Django 5.1.1 on 2025-09-24 03:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0006_alter_finishingsheet_chemical_yellowing_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='producttemplate',
            name='type',
            field=models.CharField(default='stain', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producttemplate',
            name='type_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='producttemplate',
            name='type_vi',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='producttemplate',
            name='type_zh_hant',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rowproduct',
            name='product_type_en',
            field=models.CharField(default='stain', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rowproduct',
            name='product_type_vi',
            field=models.CharField(default='stain', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rowproduct',
            name='product_type_zh_hant',
            field=models.CharField(default='stain', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sheetrow',
            name='sanding_en',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sheetrow',
            name='sanding_vi',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sheetrow',
            name='sanding_zh_hant',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sheetrow',
            name='stepname_short_en',
            field=models.CharField(default='stain', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sheetrow',
            name='stepname_short_vi',
            field=models.CharField(default='stain', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sheetrow',
            name='stepname_short_zh_hant',
            field=models.CharField(default='stain', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='steptemplate',
            name='sanding',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='steptemplate',
            name='sanding_en',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='steptemplate',
            name='sanding_vi',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='steptemplate',
            name='sanding_zh_hant',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='formulartemplate',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='formulartemplate',
            name='viscosity',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='sheetrow',
            name='spec_en',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sheetrow',
            name='spec_vi',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sheetrow',
            name='spec_zh_hant',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sheetrow',
            name='viscosity_en',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sheetrow',
            name='viscosity_vi',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sheetrow',
            name='viscosity_zh_hant',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='steptemplate',
            name='short_name',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='steptemplate',
            name='short_name_en',
            field=models.CharField(max_length=25, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='steptemplate',
            name='short_name_vi',
            field=models.CharField(max_length=25, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='steptemplate',
            name='short_name_zh_hant',
            field=models.CharField(max_length=25, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='SheetBlueprint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('blueprint', models.CharField(max_length=128)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_blueprints', to=settings.AUTH_USER_MODEL)),
                ('finishing_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blueprints', to='sheet.finishingsheet')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_blueprints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
