# Generated by Django 5.1.1 on 2025-09-20 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0006_alter_finishingsheet_chemical_yellowing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulartemplate',
            name='spray_type',
            field=models.CharField(default='spray evenly', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formulartemplate',
            name='spray_type_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='formulartemplate',
            name='spray_type_vi',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='formulartemplate',
            name='spray_type_zh_hant',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='producttemplate',
            name='type',
            field=models.CharField(default='thinner', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producttemplate',
            name='type_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='producttemplate',
            name='type_vi',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='producttemplate',
            name='type_zh_hant',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
