# Generated by Django 5.1.1 on 2025-09-24 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0007_producttemplate_type_producttemplate_type_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulartemplate',
            name='viscosity',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
