# Generated by Django 5.1.1 on 2025-09-23 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0008_sheetblueprint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulartemplate',
            name='spray_type',
        ),
        migrations.RemoveField(
            model_name='formulartemplate',
            name='spray_type_en',
        ),
        migrations.RemoveField(
            model_name='formulartemplate',
            name='spray_type_vi',
        ),
        migrations.RemoveField(
            model_name='formulartemplate',
            name='spray_type_zh_hant',
        ),
        migrations.AddField(
            model_name='sheetrow',
            name='sanding_en',
            field=models.CharField(default='#320', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sheetrow',
            name='sanding_vi',
            field=models.CharField(default='#320', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sheetrow',
            name='sanding_zh_hant',
            field=models.CharField(default='#320', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sheetrow',
            name='stepname_short_en',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sheetrow',
            name='stepname_short_vi',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sheetrow',
            name='stepname_short_zh_hant',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='steptemplate',
            name='sanding',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='steptemplate',
            name='sanding_en',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='steptemplate',
            name='sanding_vi',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='steptemplate',
            name='sanding_zh_hant',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='formulartemplate',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='steptemplate',
            name='short_name',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='steptemplate',
            name='short_name_en',
            field=models.CharField(max_length=25, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='steptemplate',
            name='short_name_vi',
            field=models.CharField(max_length=25, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='steptemplate',
            name='short_name_zh_hant',
            field=models.CharField(max_length=25, null=True, unique=True),
        ),
    ]
