# Generated by Django 5.1.1 on 2026-03-30 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0008_alter_formulartemplate_viscosity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sheetrow',
            options={'ordering': ['sheet', 'order']},
        ),
        migrations.RenameField(
            model_name='finishingsheet',
            old_name='sheen',
            new_name='sheen_level',
        ),
        migrations.RenameField(
            model_name='producttemplate',
            old_name='type',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='producttemplate',
            old_name='type_en',
            new_name='description_en',
        ),
        migrations.RenameField(
            model_name='producttemplate',
            old_name='type_vi',
            new_name='description_vi',
        ),
        migrations.RenameField(
            model_name='producttemplate',
            old_name='type_zh_hant',
            new_name='description_zh_hant',
        ),
        migrations.RenameField(
            model_name='rowproduct',
            old_name='product_type_en',
            new_name='product_description_en',
        ),
        migrations.RenameField(
            model_name='rowproduct',
            old_name='product_type_vi',
            new_name='product_description_vi',
        ),
        migrations.RenameField(
            model_name='rowproduct',
            old_name='product_type_zh_hant',
            new_name='product_description_zh_hant',
        ),
        migrations.RenameField(
            model_name='sheetrow',
            old_name='stepname_en',
            new_name='name_en',
        ),
        migrations.RenameField(
            model_name='sheetrow',
            old_name='stepname_short_en',
            new_name='name_short_en',
        ),
        migrations.RenameField(
            model_name='sheetrow',
            old_name='stepname_short_vi',
            new_name='name_short_vi',
        ),
        migrations.RenameField(
            model_name='sheetrow',
            old_name='stepname_short_zh_hant',
            new_name='name_short_zh_hant',
        ),
        migrations.RenameField(
            model_name='sheetrow',
            old_name='stepname_vi',
            new_name='name_vi',
        ),
        migrations.RenameField(
            model_name='sheetrow',
            old_name='stepname_zh_hant',
            new_name='name_zh_hant',
        ),
        migrations.RenameField(
            model_name='sheetrow',
            old_name='step_num',
            new_name='order',
        ),
        migrations.AlterUniqueTogether(
            name='sheetrow',
            unique_together={('sheet', 'order')},
        ),
        migrations.RemoveField(
            model_name='finishingsheet',
            name='name',
        ),
        migrations.RemoveField(
            model_name='rowproduct',
            name='check_result',
        ),
        migrations.RemoveField(
            model_name='rowproduct',
            name='correct_action',
        ),
        migrations.RemoveField(
            model_name='rowproduct',
            name='customer_signature',
        ),
        migrations.RemoveField(
            model_name='rowproduct',
            name='te1_signature',
        ),
        migrations.AddField(
            model_name='finishingsheet',
            name='collection',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='finishingsheet',
            name='color',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='finishingsheet',
            name='customer_color_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='finishingsheet',
            name='factory_code',
            field=models.CharField(default='99999', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='finishingsheet',
            name='furniture_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='finishingsheet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='finishing_sheets/'),
        ),
        migrations.AddField(
            model_name='finishingsheet',
            name='panel_category',
            field=models.CharField(default='Unknown', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='finishingsheet',
            name='purpose_of_usage',
            field=models.CharField(default='Unknown', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='finishingsheet',
            name='retailer_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='finishingsheet',
            name='sample_type',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='finishingsheet',
            name='substrate_surface_treatment',
            field=models.CharField(default='Unknown', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sheetrow',
            name='oven_temperature',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='sheetrow',
            name='wft',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='steptemplate',
            name='oven_temperature',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='finishingsheet',
            name='chemical_waste',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='finishingsheet',
            name='chemical_yellowing',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='finishingsheet',
            name='conveyor_speed',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='finishingsheet',
            name='dft',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='finishingsheet',
            name='finishing_code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='finishingsheet',
            name='testing',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='finishingsheet',
            name='type_of_paint',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='finishingsheet',
            name='with_panel_test',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='formulartemplate',
            name='viscosity',
            field=models.CharField(blank=True, default='Unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='formulartemplate',
            name='wft',
            field=models.CharField(blank=True, default='Unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rowproduct',
            name='qty',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='rowproduct',
            name='ratio',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='rowproduct',
            name='unit',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='sheetrow',
            name='chemical_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sheetrow',
            name='consumption',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sheetrow',
            name='hold_time',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='steptemplate',
            name='hold_time',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
