# Generated by Django 5.1.1 on 2025-09-23 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheet', '0009_remove_formulartemplate_spray_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rowproduct',
            name='product_type_en',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rowproduct',
            name='product_type_vi',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rowproduct',
            name='product_type_zh_hant',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
