# Generated by Django 5.1.1 on 2025-07-30 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_businessfunction_permission_rolepermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessfunction',
            name='name_en',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='businessfunction',
            name='name_vi',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='businessfunction',
            name='name_zh_hant',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
