# Generated by Django 5.1.1 on 2025-07-30 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_businessfunction_name_en_businessfunction_name_vi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='business_function',
            field=models.ForeignKey(default='707a4273-f61c-46e6-9c0a-f4b156b4712a', on_delete=django.db.models.deletion.PROTECT, related_name='users', to='user.businessfunction'),
            preserve_default=False,
        ),
    ]
