# Generated by Django 5.1.1 on 2025-09-07 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_business_function'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_password_changed',
            field=models.BooleanField(),
        ),
    ]
