# Generated by Django 5.1.1 on 2025-06-04 07:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('process', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255, null=True)),
                ('name_vi', models.CharField(max_length=255, null=True)),
                ('name_zh_hant', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('description_vi', models.TextField(blank=True, null=True)),
                ('description_zh_hant', models.TextField(blank=True, null=True)),
                ('state_type', models.CharField(choices=[('pending_approve', 'Pending Approve'), ('analyze', 'Analyze'), ('working', 'Working'), ('pending_review', 'Pending Review'), ('start', 'Start'), ('denied', 'Denied'), ('canceled', 'Canceled'), ('closed', 'Closed')], default='start', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_from', to='workflow_engine.state')),
                ('next_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_to', to='workflow_engine.state')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.process')),
            ],
        ),
        migrations.CreateModel(
            name='ActionTransition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.action')),
                ('transition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow_engine.transition')),
            ],
        ),
        migrations.AddConstraint(
            model_name='transition',
            constraint=models.UniqueConstraint(fields=('process', 'current_state', 'next_state'), name='unique_transition'),
        ),
        migrations.AddConstraint(
            model_name='actiontransition',
            constraint=models.UniqueConstraint(fields=('action', 'transition'), name='unique_action_transition'),
        ),
    ]
