# Generated by Django 5.1.1 on 2025-05-02 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('process', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('state_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow_engine.statetype')),
            ],
        ),
        migrations.CreateModel(
            name='Transition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_from', to='workflow_engine.state')),
                ('next_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_to', to='workflow_engine.state')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.process')),
            ],
        ),
        migrations.CreateModel(
            name='ActionTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.action')),
                ('transition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow_engine.transition')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('action', 'transition'), name='unique_action_transition')],
            },
        ),
    ]
