# Generated by Django 5.1.1 on 2025-05-03 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='is_first_state',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='is_last_state',
            field=models.BooleanField(null=True),
        ),
    ]
