# Generated by Django 5.1.1 on 2025-09-05 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='state_type',
            field=models.CharField(choices=[('pending_approve', 'Pending Approve'), ('analyze', 'Analyze'), ('working', 'Working'), ('pending_review', 'Pending Review'), ('start', 'Start'), ('denied', 'Denied'), ('canceled', 'Canceled'), ('closed', 'Closed')], max_length=255),
        ),
    ]
