# Generated by Django 5.1.1 on 2025-05-17 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_engine', '0003_remove_state_is_first_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='state_type',
            field=models.CharField(choices=[('pending_approve', 'Pending Approve'), ('analyze', 'Analyze'), ('working', 'Working'), ('pending_review', 'Pending Review'), ('start', 'Start'), ('denied', 'Denied'), ('closed', 'Closed')], default='start', max_length=255),
        ),
        migrations.DeleteModel(
            name='StateType',
        ),
    ]
