# Generated by Django 5.1.1 on 2025-05-17 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0007_process_is_deleted_alter_process_name'),
        ('workflow_engine', '0004_alter_state_state_type_delete_statetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='state_type',
            field=models.CharField(choices=[('pending_approve', 'Pending Approve'), ('analyze', 'Analyze'), ('working', 'Working'), ('pending_review', 'Pending Review'), ('start', 'Start'), ('denied', 'Denied'), ('canceled', 'Canceled'), ('closed', 'Closed')], default='start', max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='transition',
            unique_together={('process', 'current_state', 'next_state')},
        ),
    ]
