# Generated by Django 5.1.1 on 2025-05-24 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0010_alter_processuser_process_alter_processuser_user'),
        ('workflow_engine', '0006_actiontransition_created_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transition',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='transition',
            constraint=models.UniqueConstraint(fields=('process', 'current_state', 'next_state'), name='unique_transition'),
        ),
    ]
